---
title: "About us"
format: html
---

(IKKE FERDIG)

We are second- and third-year Bachelor's students in Political Science at the University of Stavanger. This project was carried out as a voluntary project under the supervision of Associate Professor [Carlo Knotz](https://www.uis.no/nb/profile/carlo-michael-knotz-0).

## Project Members

::: columns
::: column
**Aud Statle Nævdal** 

3rd year Bachelor student (at the time of the project).

Aud's contributions include:

-  Executing the data collection strategy.

-  Contributing to the development and refinement of the survey questions.

-  Contributing to the authoring of the analysis and results section.

:::

::: column
**[Awaatef Hassan](https://www.linkedin.com/in/awaatef-abdullah-hassan-6b1386345?utm_source=share_via&utm_content=profile&utm_medium=member_ios)** 

2nd year Bachelor student (at the time of the project).

Awaatef's contributions include:

-  Executing the data collection strategy.

-  Contributing to the development and refinement of the survey questions.

-  Contributing to the authoring of the theoretical framework. 

-  Authoring the project information and introductory content for the homepage.

:::
:::

<br>

::: columns
::: column
**[Marie Langeland](https://www.linkedin.com/in/marie-langeland)** 

3rd year Bachelor student (at the time of the project).

Marie's contributions include:

-  Developing the responsive landing page and randomization function for assigning respondents to the two survey versions.

-  Executing the data collection strategy.

-  Creating and managing the surveys.

-  Contributing to the development and refinement of the survey questions.

-  Managing data cleaning, including filtering and recoding variables for analysis.

-  Performing the statistical analysis and data visualization in R.

-  Building and managing the Quarto website for the project.

-  Authoring the methodology and experimental design section.

-  Contributing to the authoring of the analysis and results section.

:::

::: column
**[Norman Sunde](https://www.linkedin.com/in/norman-sunde)** 

2nd year Bachelor student (at the time of the project).

Norman's contributions include:

-  Executing the data collection strategy.

-  Contributing to the development and refinement of the survey questions.

-  Authoring the documentation of the data collection process.

<br>

**[William Thengs Egeli](https://www.linkedin.com/in/william-thengs-egeli-4204b8356)** 

3rd year Bachelor student (at the time of the project).

William's contributions include:

-  Executing the data collection strategy.

-  Contributing to the development and refinement of the survey questions.

-  Contributing to the authoring of the theoretical framework and research design.

:::
:::

<br>

::: columns
::: column
**Zainab Ali** 

2nd year Bachelor student (at the time of the project).

Zainab's contributions include:

-  Executing the data collection strategy.

-  Contributing to the development and refinement of the survey questions.

-  Contributing to the authoring of the theoretical framework. 

:::

::: column
:::
:::
